platform:ios, '8.0'

pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'NJKWebViewProgress'
pod 'SDWebImage'
pod 'GUITabPagerViewController', '~> 0.0.7'
pod 'GoogleMaps'
pod 'AFNetworking', '~> 2.4.1'
pod 'BDBOAuth1Manager', '~> 1.4.0'
pod 'FoldingTabBar'
